name: NXThemesInstaller
on:
  workflow_dispatch:
  push:
    branches: [ master, githubCI ]
    paths:
      - SwitchThemesNX/**
      # This file is included in the c++ codebase to load the json fixes
      - SwitchThemesCommon/NewFirmFixesJsons.cs
  pull_request:
    branches: [ master ]
    paths:
      - SwitchThemesNX/**
      - SwitchThemesCommon/NewFirmFixesJsons.cs
jobs:
  Build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch build script
      run: |
        sudo apt-get update
        sudo apt-get install -y p7zip-full
        cd $GITHUB_WORKSPACE/SwitchThemesNX/
        chmod +x scripts/cibuild.sh
        scripts/cibuild.sh -j4
    - name: Package artifacts
      run: |
        cd $GITHUB_WORKSPACE/SwitchThemesNX/
        7z a -y -mx=7 SwitchThemesNX.elf.7z SwitchThemesNX.elf
        mkdir artifacts
        mv SwitchThemesNX.nro SwitchThemesNX.elf.7z artifacts/
    - uses: actions/upload-artifact@v4
      with:
        name: InstallerBuild
        path: ${{ github.workspace }}/SwitchThemesNX/artifacts/
